from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
from datetime import datetime

def create_policy_brief(data: dict) -> io.BytesIO:
    """
    Generates a professional Government-style .docx brief from the analysis data.
    """
    doc = Document()
    
    # --- STYLE: HEADER ---
    header = doc.sections[0].header
    p = header.paragraphs[0]
    p.text = "OFFICIAL SENSITIVE | CABINET-IN-CONFIDENCE"
    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    
    # --- TITLE ---
    title = doc.add_heading('Ministerial Decision Brief', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph(f"Generated by Xaana.AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph("_" * 70) # Horizontal Line

    # --- SECTION 1: EXECUTIVE SUMMARY ---
    doc.add_heading('1. Executive Summary', level=1)
    doc.add_paragraph(data.get("about", "No summary provided."))

    # --- SECTION 2: AUDIT DATA (The "Hard Facts" Table) ---
    doc.add_heading('2. Fiscal & Legal Audit (Automated)', level=1)
    
    # Create a table for the Hard Data
    hard_data = data.get("hard_data", {})
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Category'
    hdr_cells[1].text = 'Extracted Details'
    
    # Helper to add rows
    def add_row(label, items):
        if items:
            row_cells = table.add_row().cells
            row_cells[0].text = label
            row_cells[1].text = ", ".join(items)

    add_row("Budgetary Mentions", hard_data.get("budget_mentions", []))
    add_row("Legal References", hard_data.get("legal_references", []))
    add_row("Key Dates", hard_data.get("important_dates", []))
    
    if not any(hard_data.values()):
        doc.add_paragraph("No specific entities detected by audit layer.")

    # --- SECTION 3: KEY DECISIONS ---
    doc.add_heading('3. Key Decisions & Recommendations', level=1)
    if data.get("decisions"):
        for item in data.get("decisions", []):
            doc.add_paragraph(item, style='List Bullet')
    else:
        doc.add_paragraph("No decisions identified.")

    # --- SECTION 4: RISK ASSESSMENT ---
    doc.add_heading('4. Risk Analysis', level=1)
    if data.get("risks"):
        for item in data.get("risks", []):
            p = doc.add_paragraph(item, style='List Bullet')
            # Highlight high risks in Red text
            if "high" in item.lower() or "critical" in item.lower():
                run = p.runs[0]
                run.font.color.rgb = RGBColor(255, 0, 0)
                run.bold = True
    else:
        doc.add_paragraph("No immediate risks identified.")

    # --- SECTION 5: IMPACT STATEMENT ---
    doc.add_heading('5. Operational Impact', level=1)
    doc.add_paragraph(data.get("impact", "No impact statement generated."))

    # --- SAVE TO BUFFER ---
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer